<?php
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__ . '/../../translate/lib/db.php';
require_once __DIR__ . '/../../translate/lib/auth.php';
require_once __DIR__ . '/../../translate/lib/generated_data.php';

require_admin();

// Generated by tools/scripts/fetch-admin-playerdata.js on the normal CI
// schedule (every hour) and published into Postgres like everything else in
// generated_data - see that script's header comment for why this moved off
// a live-per-request SFTP fetch (it was too fragile running inside the web
// container: OOM-kill risk, signal-handling edge cases, timeouts racing
// against real network latency). Postgres (never the public repo) still
// preserves the reason this was never a static file: home/death/grave
// locations and full grave inventories are more sensitive than anything
// else generated here.
serve_generated_data_with_etag(get_generated_data('admin-playerdata'));
